### ISSUE TITLE
can't work `truffle init` 

### ISSUE THREAD

**Issue by tommy96** [truffle-box/bare-box#13]
<img width="1137" alt="2018-12-20 20 57 45" src="https://user-images.githubusercontent.com/11209657/50284188-92bfdc00-049b-11e9-9eb2-ddc860b85497.png">

**Comment by tommy96** [comment]
sorry, I can fix by update truffle

**Comment by alexchaps** [comment]
I have the same error with `truffle init`:

```
Downloading...
Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
