### ISSUE TITLE
 On using truffle init , i am getting the following- Downloading... Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.     at Request._callback (C:\Users\Harshit\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:313432:23)     at Request.self.callback (C:\Users\Harshit\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:284800:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (C:\Users\Harshit\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:285777:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (C:\Users\Harshit\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:285699:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)

### ISSUE THREAD

**Issue by Harshitb1** [truffle-box/bare-box#15]

**Comment by ouoabcde** [comment]
I had same error, too. Others recommend to use new Truffle version, but I want to use Truffle v4 because I use this version on other projects.
