### ISSUE TITLE
Truffle v4.1.13 not working

### ISSUE THREAD

**Issue by CarlosLanderas** [truffle-box/bare-box#18]
Truffle Version 4.X stopped working with latest repository changes.

I am using the following version:

Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)

And when you try to create a new project with truffle init it is not working:
```
 truffle init
Downloading...
Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (C:\Users\Carlos Landeras\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-box\lib\utils\unbox.js:50:1)
    at Request.self.callback (C:\Users\Carlos Landeras\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\Carlos Landeras\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:1157:1)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\Carlos Landeras\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:1079:1)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Please, this should be fixed as not everyone is running on the last version.
Thank you very much.

**Comment by zmitton** [comment]
running `Truffle v5.0.0-beta.0 (core: 5.0.0-beta.0)` same issue

**Comment by pedrojn-dev** [comment]
I have the same problem, please is there any solution?
